services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    environment:
      - QDB_TELEMETRY_ENABLED=false
    volumes:
      - questdb-data:/var/lib/questdb

volumes:
  questdb-data:
